name: UnitTest CI

on:
  pull_request:
    branches: [ '*' ]

jobs:
  unittest-job:
    runs-on: ubuntu-latest
    container: node:16

    steps:
    - name: Install deps
      run: NODE_ENV=development npm i
    - name: Test
      run: CI=true npm test
